#!/bin/bash

source "./themes/$1/setup.sh"

declare -a all=( $(./render "$1") )

put_color() {
  local hex
  if [[ "${#2}" -eq 7 ]]
  then
    hex="$2"
  else
    hex="${all[$2]}"
  fi
  local r="${hex:1:2}"
  local g="${hex:3:2}"
  local b="${hex:5:2}"
  local fg_bg
  case $1 in
    fg) fg_bg=38 ;;
    bg) fg_bg=48 ;;
  esac
  echo -en "\x1b[$fg_bg;2;$((16#$r));$((16#$g));$((16#$b))m"
}

preview_octet() {
  local fg_color
  print_bg '  '
  for c in {0..7}
  do
    case "$1" in
      rel) printf "$(put_color bg "$(( $c + $2 ))")" ;;
      abs) print_bg '' ;;
    esac
    case "$3" in
      rel) fg_color="$(( $c + $4 ))" ;;
      abs) fg_color="$4" ;;
    esac
    printf "$(put_color fg "$fg_color")"
    printf ' %03d ' $fg_color
    printf "$(tput sgr0)"
    print_bg '  '
    printf "$(tput sgr0)"
  done
  echo
}

print_bg() {
  printf "$(put_color bg "#$theme_background_color")$1"
}

preview_gap() {
  printf "$(put_color bg "#$theme_background_color")"
  printf '%*s' 58
  printf "$(tput sgr0)"
  echo
}

echo "$(tput sgr0)"

preview_gap

# preview function must be defined in theme's setup script
case $(type -t theme_preview) in
  function)
    theme_preview
    ;;
  *)
    >&2 echo 'preview function not defined'
    exit 1
    ;;
esac
preview_gap
