#!/bin/bash

source "./themes/$1/setup.sh"

preview_octet() {
  local fg_color
  printf '  '
  for c in {0..7}
  do
    case "$1" in
      rel) printf "$(tput setab "$(( $c + $2 ))")" ;;
      abs) ;;
    esac
    case "$3" in
      rel) fg_color="$(( $c + $4 ))" ;;
      abs) fg_color="$4" ;;
    esac
    printf "$(tput setaf "$fg_color")"
    printf ' %03d ' $fg_color
    printf "$(tput sgr0)  "
  done
  echo
}

preview_gap() {
  echo
}

echo "$(tput sgr0)"

# preview function must be defined in theme's setup script
case $(type -t theme_preview) in
  function)
    theme_preview
    ;;
  *)
    >&2 echo 'preview function not defined'
    exit 1
    ;;
esac

echo
